/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-sequelize6 dev) on 2021-09-28 08:19:56.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Address extends Model {
}

module.exports = (sequelize) => {
  return Address.init({
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false
    },
    validator_id: {
      type: DataTypes.INTEGER
    },
    address: {
      type: DataTypes.STRING(191)
    }
  }, {
    sequelize: sequelize,
    modelName: 'Address',
    tableName: 'addresses',
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })
}
