/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-sequelize6 dev) on 2021-10-16 04:49:05.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class MissedBlock extends Model {
}

module.exports = (sequelize) => {
  return MissedBlock.init({
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    height: {
      type: DataTypes.INTEGER
    },
    operator_address: {
      type: DataTypes.STRING(191)
    }
  }, {
    sequelize: sequelize,
    modelName: 'MissedBlock',
    tableName: 'missed_blocks',
    indexes: [
      {
        name: 'operator_address_indexes',
        fields: ['operator_address']
      }
    ],
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })
}
