/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-sequelize6 dev) on 2021-10-16 15:10:10.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class PointHistory extends Model {
}

module.exports = (sequelize) => {
  return PointHistory.init({
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    validatorId: {
      type: DataTypes.INTEGER
    },
    missionId: {
      type: DataTypes.INTEGER
    }
  }, {
    sequelize: sequelize,
    modelName: 'PointHistory',
    tableName: 'point_histories',
    indexes: [
      {
        name: 'validator_id_indexes',
        fields: ['validator_id']
      },
      {
        name: 'validator_id_mission_id_unique',
        fields: ['validator_id', 'mission_id'],
        unique: true
      }
    ],
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })
}
