/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-sequelize6 dev) on 2021-09-27 06:20:21.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Validator extends Model {
}

module.exports = (sequelize) => {
  return Validator.init({
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false
    },
    operator_address: {
      type: DataTypes.STRING(191)
    },
    moniker: {
      type: DataTypes.STRING(191)
    }
  }, {
    sequelize: sequelize,
    modelName: 'Validator',
    tableName: 'validators',
    indexes: [
      {
        name: 'operator_address_UNIQUE',
        fields: ['operator_address'],
        unique: true
      }
    ],
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })
}
